//! # axotyped
//!
//! Auto-generate typed TypeScript API clients from Axum route metadata.
//!
//! This crate provides:
//! - A declarative `api_routes!` macro for defining route metadata
//! - A TypeScript client code generator that produces typed fetch wrappers
//! - A `check()` function for CI that fails if the generated client is stale
//!
//! ## Zero Dependencies
//!
//! This crate has no external dependencies — it uses only `std`.
//! Type generation (the actual `.ts` type files) is handled by [`ts-rs`](https://crates.io/crates/ts-rs)
//! in the consuming crate.
//!
//! ## Quick Start
//!
//! ```rust
//! use axotyped::{api_routes, RouteCollection};
//!
//! fn my_routes() -> RouteCollection {
//!     api_routes! {
//!         @group users
//!
//!         list: GET "/users" [auth]
//!             -> UsersResponse;
//!         getById: GET "/users/{id}" [auth]
//!             -> UserResponse;
//!         create: POST "/users" [auth]
//!             body: CreateUserRequest -> UserResponse;
//!     }
//! }
//! ```

mod generator;
#[macro_use]
mod macros;
mod types;

#[cfg(feature = "axum")]
mod builder;

// Re-export public API
pub use generator::{CheckError, GeneratorConfig, check, generate, generate_to_file};
pub use types::{
    HttpMethod, PathParam, RouteCollection, RouteDefinition, TypeRegistry, extract_path_params,
};

#[cfg(feature = "axum")]
pub use builder::{ApiRouter, MaybeTs, RouteBuilder, WsRouteBuilder};

// Re-export the #[endpoint] attribute macro and register!() call-site macro.
#[cfg(feature = "axum")]
pub use axotyped_macros::{endpoint, register};

// Re-export ts-rs surface so consuming crates can use the derive macro and trait
// without a direct ts-rs dependency. When the `companion-crate` feature is enabled
// in ts-rs-macros, the derive macro generates code referencing `::axotyped` paths,
// so all ts-rs types must be accessible through this crate.
#[cfg(feature = "ts-rs")]
pub use ts_rs::*;

// ---------------------------------------------------------------------------
// EndpointMeta — trait for auto-inferred route type metadata
// ---------------------------------------------------------------------------

/// Trait generated by `#[endpoint]` to carry inferred type metadata.
///
/// The proc-macro creates a companion struct (`<fn_name>__EndpointMeta`) that
/// implements this trait. The builder calls `apply()` when constructing the
/// route to populate the `RouteDefinition` with the extracted body/response/query types.
///
/// You should not implement this trait manually — use `#[endpoint]` on your
/// handler functions instead.
pub trait EndpointMeta: Sized {
    /// Apply inferred type metadata to a route definition and register types
    /// for TypeScript export.
    fn apply(def: &mut RouteDefinition, registry: &mut RouteCollection);
}

// ---------------------------------------------------------------------------
// __private — internals used by the #[endpoint] and register!() macros
// ---------------------------------------------------------------------------

/// Internal helpers used by generated code. Not part of the public API.
#[cfg(feature = "axum")]
pub mod __private {
    pub use crate::builder::{collect_type, set_pending_meta, type_string};
}
