//! # axotyped
//!
//! Auto-generate typed TypeScript API clients from Axum route metadata.
//!
//! This crate provides:
//! - An `ApiRouter` builder that creates both an Axum router and route metadata
//! - `#[endpoint]` and `register!()` macros for automatic type inference
//! - A TypeScript client code generator that produces typed fetch wrappers
//! - A `check()` function for CI that fails if the generated client is stale
//!
//! ## Quick Start
//!
//! ```rust,ignore
//! use axotyped::{ApiRouter, endpoint, register};
//!
//! #[endpoint]
//! pub async fn list_projects(
//!     State(state): State<AppState>,
//! ) -> Result<Json<Vec<ProjectResponse>>, StatusCode> {
//!     // ...
//! }
//!
//! let (router, routes) = ApiRouter::<AppState>::new()
//!     .group_with("admin", |g| {
//!         g.auth_all()
//!          .get("/projects", register!(list_projects))
//!              .done()
//!     })
//!     .build();
//! ```

mod generator;
mod types;
mod builder;
#[macro_use]
mod macros;

// Re-export public API
pub use generator::{CheckError, GeneratorConfig, check, generate, generate_to_file};
pub use types::{
    HttpMethod, PathParam, RouteCollection, RouteDefinition, TypeRegistry, extract_path_params,
};

pub use builder::{ApiRouter, MaybeTs, RouteBuilder, WsRouteBuilder};

// Re-export the #[endpoint] attribute macro and register!() call-site macro.
pub use axotyped_macros::{endpoint, register};

// ts-rs integration: TS trait, derive macro, and all standard type impls.
// Gated behind the `ts-rs` feature. The derive macro lives in axotyped-macros
// and generates code referencing `::axotyped` paths.
#[cfg(feature = "ts-rs")]
mod ts;

// Re-export all ts-rs types so generated code can reference them as
// `::axotyped::TS`, `::axotyped::Config`, etc.
#[cfg(feature = "ts-rs")]
pub use ts::*;

// ---------------------------------------------------------------------------
// EndpointMeta — trait for auto-inferred route type metadata
// ---------------------------------------------------------------------------

/// Trait generated by `#[endpoint]` to carry inferred type metadata.
///
/// The proc-macro creates a companion struct (`<fn_name>__EndpointMeta`) that
/// implements this trait. The builder calls `apply()` when constructing the
/// route to populate the `RouteDefinition` with the extracted body/response/query types.
///
/// You should not implement this trait manually — use `#[endpoint]` on your
/// handler functions instead.
pub trait EndpointMeta: Sized {
    /// Apply inferred type metadata to a route definition and register types
    /// for TypeScript export.
    fn apply(def: &mut RouteDefinition, registry: &mut RouteCollection);
}

// ---------------------------------------------------------------------------
// __private — internals used by the #[endpoint] and register!() macros
// ---------------------------------------------------------------------------

/// Internal helpers used by generated code. Not part of the public API.
pub mod __private {
    pub use crate::builder::{collect_type, set_pending_meta, type_string};
}
